[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/server"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"
